"use client";

import { useState, useEffect } from "react";
import { TimelineReplay } from "../components/TimelineReplay";
import { FlowVisualization } from "../components/FlowVisualization";
import type { AdlEvent, AdlEventsData, RawRow } from "../types/events";
import Papa from "papaparse";

// Load from public/data (generated by scripts in this repo)
const CANONICAL_JSON_URL = "/data/adl_events.json";
const FLOW_DATA_URL = "/data/adl_flow_data.json";
const CANONICAL_CSV_URL = "https://raw.githubusercontent.com/ConejoCapital/HyperMultiAssetedADL/main/data/canonical/cash-only%20balances%20ADL%20event%20orderbook%202025-10-10/adl_detailed_analysis_REALTIME.csv";

type ViewMode = "flow" | "timeline";

export default function HomePage() {
  const [adlEvents, setAdlEvents] = useState<AdlEvent[]>([]);
  const [flowData, setFlowData] = useState<any>(null);
  const [metadata, setMetadata] = useState<AdlEventsData["metadata"] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<ViewMode>("flow");
  const [currentTimeMs, setCurrentTimeMs] = useState(0);
  const [timeRange, setTimeRange] = useState<{ start: number; end: number }>({ start: 0, end: 0 });

  useEffect(() => {
    // Load flow data first (for new visualization)
    setLoading(true);
    setError(null);

    // Load flow data
    fetch(FLOW_DATA_URL)
      .then((res) => {
        if (!res.ok) throw new Error("Flow data not found");
        return res.json();
      })
      .then((data) => {
        setFlowData(data);
        setTimeRange(data.metadata.timeRange);
      })
      .catch((err) => {
        console.warn("Flow data not available:", err);
      });

    // Also load events for timeline view
    fetch(CANONICAL_JSON_URL)
      .then((res) => {
        if (res.ok) {
          return res.json();
        }
        throw new Error("JSON not found, falling back to CSV");
      })
      .then((data: AdlEventsData) => {
        setAdlEvents(data.events);
        setMetadata(data.metadata);
        setTimeRange(data.metadata.timeRange);
        setLoading(false);
      })
      .catch(() => {
        // Fallback to CSV parsing
        console.log("JSON not available, parsing CSV...");
        Papa.parse<RawRow>(CANONICAL_CSV_URL, {
          download: true,
          header: true,
          dynamicTyping: true,
          skipEmptyLines: true,
          complete: (result) => {
            try {
              const parsedRows = (result.data || []) as RawRow[];
              if (!parsedRows.length) {
                setError("No data found in CSV");
                setLoading(false);
                return;
              }

              // Convert CSV rows to AdlEvent format
              const events: AdlEvent[] = [];
              for (const row of parsedRows) {
                const timestamp = parseTimestamp(row.time);
                if (!timestamp) continue;

                const notional = getNumericValue(row, ["adl_notional", "notional", "usd"]);
                if (!notional || notional <= 0) continue;

                events.push({
                  timestamp,
                  timestampISO: new Date(timestamp).toISOString(),
                  asset: getStringValue(row, ["coin", "asset", "ticker"]) || "UNKNOWN",
                  notionalUsd: notional,
                  side: determineSide(row),
                  liquidatedUserId: getStringValue(row, ["liquidated_user"]) || "",
                  targetUserId: getStringValue(row, ["user"]) || "",
                  batchId: String(Math.floor(timestamp / 1000)),
                });
              }

              events.sort((a, b) => a.timestamp - b.timestamp);

              if (events.length) {
                setAdlEvents(events);
                setMetadata({
                  eventCount: events.length,
                  timeRange: {
                    start: events[0].timestamp,
                    end: events[events.length - 1].timestamp,
                  },
                  totalNotionalUsd: events.reduce((sum, e) => sum + e.notionalUsd, 0),
                  uniqueAssets: new Set(events.map((e) => e.asset)).size,
                  uniqueAccounts: new Set(events.filter((e) => e.targetUserId).map((e) => e.targetUserId)).size,
                });
                setTimeRange({
                  start: events[0].timestamp,
                  end: events[events.length - 1].timestamp,
                });
              }
              setLoading(false);
            } catch (err) {
              setError(err instanceof Error ? err.message : "Failed to parse CSV");
              setLoading(false);
            }
          },
          error: (err) => {
            setError(err.message || "Failed to load data");
            setLoading(false);
          },
        });
      });
  }, []);

  return (
    <main className="min-h-screen px-4 py-8 sm:px-8 sm:py-10 bg-slate-950 text-slate-50">
      <div className="max-w-7xl mx-auto space-y-6">
        <header className="space-y-2">
          <h1 className="text-2xl sm:text-3xl font-semibold">
            Hyperliquid ADL Visualizer
          </h1>
          <p className="text-sm text-slate-400 max-w-2xl">
            Interactive replay of the October 10, 2025 ADL cascade. Data loaded from{" "}
            <a
              href="https://github.com/ConejoCapital/HyperMultiAssetedADL"
              className="text-emerald-400 hover:underline"
              target="_blank"
              rel="noreferrer"
            >
              HyperMultiAssetedADL
            </a>{" "}
            canonical dataset.
          </p>
        </header>

        {loading && (
          <div className="border border-slate-700/70 rounded-2xl p-6 bg-slate-900/60 text-center">
            <div className="text-slate-400">Loading ADL data...</div>
          </div>
        )}

        {error && (
          <div className="border border-red-700/70 rounded-2xl p-6 bg-red-900/20 text-red-400">
            <div className="font-semibold">Error loading data</div>
            <div className="text-sm mt-2">{error}</div>
          </div>
        )}

        {adlEvents.length > 0 && metadata && (
          <>
            {/* View mode selector */}
            <div className="flex items-center gap-4 border border-slate-700/70 rounded-2xl p-4 bg-slate-900/60">
              <div className="text-sm text-slate-400">View:</div>
              <button
                type="button"
                className={`px-4 py-2 rounded-xl text-sm font-medium transition ${
                  viewMode === "flow"
                    ? "bg-gradient-to-r from-purple-500 to-pink-500 text-white shadow-lg"
                    : "bg-slate-800 hover:bg-slate-700 text-slate-300"
                }`}
                onClick={() => setViewMode("flow")}
              >
                Flow Visualization
              </button>
              <button
                type="button"
                className={`px-4 py-2 rounded-xl text-sm font-medium transition ${
                  viewMode === "timeline"
                    ? "bg-emerald-500 text-slate-950"
                    : "bg-slate-800 hover:bg-slate-700 text-slate-300"
                }`}
                onClick={() => setViewMode("timeline")}
              >
                Timeline Replay
              </button>
              {metadata && (
                <div className="ml-auto text-xs text-slate-500">
                  {metadata.eventCount.toLocaleString()} events • ${metadata.totalNotionalUsd.toLocaleString(undefined, {
                    maximumFractionDigits: 0,
                  })} total notional
                </div>
              )}
            </div>

            {/* Flow visualization (new, colorful) */}
            {viewMode === "flow" && flowData && (
              <FlowVisualization
                data={flowData}
                currentTimeMs={currentTimeMs}
              />
            )}

            {/* Timeline view */}
            {viewMode === "timeline" && adlEvents.length > 0 && (
              <TimelineReplay
                events={adlEvents}
                onTimeUpdate={setCurrentTimeMs}
                timeRange={timeRange}
              />
            )}
          </>
        )}
      </div>
    </main>
  );
}

// Helper functions
function parseTimestamp(value: any): number | null {
  if (typeof value === "number") {
    return value < 1e12 ? value * 1000 : value;
  }
  if (typeof value === "string") {
    const num = Number(value);
    if (!isNaN(num) && num > 0) {
      return num < 1e12 ? num * 1000 : num;
    }
    const date = new Date(value);
    if (!isNaN(date.getTime())) {
      return date.getTime();
    }
  }
  return null;
}

function getNumericValue(row: RawRow, keys: string[]): number | null {
  for (const key of keys) {
    if (key in row && row[key] != null) {
      const val = typeof row[key] === "number" ? row[key] : Number(row[key]);
      if (!isNaN(val) && isFinite(val)) {
        return val;
      }
    }
  }
  return null;
}

function getStringValue(row: RawRow, keys: string[]): string | null {
  for (const key of keys) {
    if (key in row && row[key] != null) {
      return String(row[key]);
    }
  }
  return null;
}

function determineSide(row: RawRow): "long" | "short" {
  const sideStr = getStringValue(row, ["side", "direction"])?.toLowerCase() || "";
  if (sideStr.includes("long") || sideStr.includes("buy") || sideStr === "b") {
    return "long";
  }
  if (sideStr.includes("short") || sideStr.includes("sell") || sideStr === "a") {
    return "short";
  }
  return "long";
}
